### ISSUE TITLE
GA : pip-install take an 1hour 

### ISSUE THREAD

**Issue by raphaelauv** [flexflow/FlexFlow#1035]
the github action : pip-install  take around an hour to perform

is that normal ? or some caching would be possible ?

**Comment by goliaro** [comment]
The free github runners only have 2 cores, of which we can only use 1 for building (we tried using both before, but it would run out of memory), so the build time is naturally quite slow. We're currently working on restoring the mechanism to pre-build the Legion library, save it on S3 (or somewhere else), and link to the prebuilt library instead of having to compile it from scratch every time. Once we do that, building FlexFlow in CI should take 75% less time

**Comment by lockshaw** [comment]
Tracking in https://github.com/flexflow/FlexFlow/pull/1042
