### ISSUE TITLE
error occur when executing with pytorch interface

### ISSUE THREAD

**Issue by MiZhangWhuer** [flexflow/FlexFlow#154]
I've successfully compile the entire project from source code and everything goes well with the scripts in python/native/ folder. However, when running with PyTorch as the front end like this:
 
python/flexflow_python examples/python/pytorch/resnet.py -ll:py 1 -ll:gpu 1 -ll:fsize 24000 -ll:zsize 15000 --epochs 10

The error occurs: 
[0 - 7ff6a4e9da40]    2.538880 {5}{gpu}: ERROR: The binary was compiled for the wrong GPU architecture. Update the 'GPU_ARCH' flag at the top of runtime/runtime.mk to match/include your current GPU architecture (70).

I tried to export GPU_ARC=70, but it doesn't work. How can I fix the bug? Is there any instruction?

**Comment by eddy16112** [comment]
You will need to make sure GPU_ARCH matches your GPU. Here is the list of compute compatibility https://en.wikipedia.org/wiki/CUDA.

**Comment by MiZhangWhuer** [comment]
> You will need to make sure GPU_ARCH matches your GPU. Here is the list of compute compatibility https://en.wikipedia.org/wiki/CUDA.

Thanks for the repaid replay. According to your instruction, I found that Tesla V100 has the computation compatibility of 70. I set the GPU_ARC to 70, but in vain. Do you have any other suggestion?

**Comment by eddy16112** [comment]
GPU_ARCH not GPU_ARC

**Comment by MiZhangWhuer** [comment]
> GPU_ARCH not GPU_ARC

Thanks for the replay. Another question is the GPU assertion error when executing native python script. Could you give me some advices?

https://github.com/flexflow/FlexFlow/issues/155

**Comment by knagrecha** [comment]
Follow up on this, did you just export GPU_ARCH=xx ? Or actually update one of the FlexFlow config files?

**Comment by MiZhangWhuer** [comment]
> Follow up on this, did you just export GPU_ARCH=xx ? Or actually update one of the FlexFlow config files?

Not exactly. I re-organize the entire project with CMake and setting the default environment by CMakeLists.txt. It can then run successfully.

**Comment by knagrecha** [comment]
Can you provide some guidance on what you reorganized/how? I am running into the same error and the exports don’t seem to fix anything. Did you change the Legion Cmake files maybe?

**Comment by MiZhangWhuer** [comment]
> Follow up on this, did you just export GPU_ARCH=xx ? Or actually update one of the FlexFlow config files?

Another issue is the version of PyTorch that is employed. It seems that the PyTorch should be >=1.5.0 in the current FlexFlow.

**Comment by MiZhangWhuer** [comment]
> Can you provide some guidance on what you reorganized/how? I am running into the same error and the exports don’t seem to fix anything. Did you change the Legion Cmake files maybe?

I did not change the Legion CMake files, instead I change the CMakeLists.txt of FlexFlow. I will release the whole project by the next month if it has already run on our project.

**Comment by fdouglis** [comment]
What did you change in CMakeLists.txt to override GPU_ARCH?  I tried this, but it didn't seem to have any effect.

**Comment by fdouglis** [comment]
To follow up on my own comment, while I saw references to setting GPU_ARCH, I also saw in the build instructions FF_CUDA_ARCH.  I tried setting that to the one {gpu} complained about, and indeed I see if I make with VERBOSE that it is invoking `-gencode arch=compute_75,code=sm_75 ` -- yet the application still dies and complains it needs to built for 75.

**Comment by jiazhihao** [comment]
If you saw `-gencode arch=compute_75,code=sm_75`, you should be building FlexFlow with the expected GPU architecture. Can you confirm that `-gencode arch=compute_75,code=sm_75` is present when compiling both Legion and FlexFlow source code? This mean for each source code compiled with nvcc, you should see the same GPU architecture number.

**Comment by knagrecha** [comment]
I attempted the same approach as @fdouglis and was able to reproduce their issue. I set FF_CUDA_ARCH to 61 for Pascal, and ran make with verbose. I saw that --gencode arch=compute_61,code=sm_61 was present throughout the logs. Yet the error still claims that I have compiled for the wrong architecture. 


Here is an exact list of the steps I took on a fresh setup with 2 GTX 1080s.

1. git clone --recursive https://github.com/flexflow/FlexFlow.git
2. Modified config/config.linux to uncomment FF_CUDA_ARCH, and set the line to be FF_CUDA_ARCH=60
3. cd FlexFlow, mkdir build, cd build
4. ../config/config.linux
5. make
6. export FF_HOME=/home/jovyan/FlexFlow   (I am on Kubernetes with a jupyterlab docker image)
7. cd ../python
8. ./flexflow_python ../examples/python/pytorch/mnist_mlp_torch.py -ll:py 1 -ll:gpu 2 -ll:fsize 7500 -ll:zsize 11000

Output: [0 - 7fe7a56edfc0]    2.695784 {5}{gpu}: ERROR: The binary was compiled for the wrong GPU architecture. Update the 'GPU_ARCH' flag at the top of runtime/runtime.mk to match/include your current GPU architecture (61).



If it will help I can attach a log of the verbose Makefile output. One suggestion I have for the error message...maybe it could state which GPU architecture the binary was actually compiled for? Could help with debugging.

**Comment by fdouglis** [comment]
It's worth noting that when I backed out my changes and started again, I could not reproduce this issue.  But it's reassuring in some sense that someone else saw it too!

**Comment by knagrecha** [comment]
So you were able to get it to work? Starting to wonder if maybe I have misunderstood something in the install instructions...this does not seem to be a common issue users are running into.

**Comment by fdouglis** [comment]
Right.  I mentioned this is the keras channel because that was where I ran into trouble.  It consistently failed, but I started with a cleaner build and it ran OK.  My guess here, but it's only a guess, is that when you hit that trouble and then start adding the new flag, even when rerunning cmake, there is some stale state confusing it.

**Comment by DavidPeleg6** [comment]
I have also come across the same issue when executing pytorch frontend scripts

**Comment by act-reds** [comment]
Hey, I have exactly the same issue, and I followed the basic installation... Everything is running smooth for native and keras examples but the following error appears when running pytorch examples : 
 ERROR: The binary was compiled for the wrong GPU architecture. Update the 'GPU_ARCH' flag at the top of runtime/runtime.mk to match/include your current GPU architecture (75).
Aborted (core dumped)

I checked that everything is alright and compiled with the needed flags, which is the case (VERBOSE=1). 

If anyone has an advice to overcome this or even some known issues to check, it would be really helpful.

**Comment by MiZhangWhuer** [comment]
I suggest you to give up this repository and it has not been updated for a long time. I am working on another project called LuoJiaNet, which enables users set parallelism easily. It will be released in the next month. Looking forward further communication !

在 2022-04-06 19:18:42，act-reds ***@***.***> 写道：


Hey, I have exactly the same issue, and I followed the basic installation... Everything is running smooth for native and keras examples but the following error appears when running pytorch examples :
ERROR: The binary was compiled for the wrong GPU architecture. Update the 'GPU_ARCH' flag at the top of runtime/runtime.mk to match/include your current GPU architecture (75).
Aborted (core dumped)

I checked that everything is alright and compiled with the needed flags, which is the case (VERBOSE=1).

If anyone has an advice to overcome this or even some known issues to check, it would be really helpful.

**Comment by eddy16112** [comment]
@act-reds The binary is generated from this file 
https://github.com/flexflow/FlexFlow/blob/master/python/main.cc
There is really no gpu arch check in python code. 

Using FlexFlow on Pytorch does not mean you can actually run Pytorch code directly. There are two ways:
1. Frist, convert the Pytorch model into IR (file) that can be recognized by FlexFlow.
Run this file, https://github.com/flexflow/FlexFlow/blob/master/examples/python/pytorch/mnist_mlp_torch.py, in this example, we convert the MLP model into a file named mlp.ff
Second, load the file into FlexFlow, and use FlexFlow to train the model. 
Run this file, https://github.com/flexflow/FlexFlow/blob/master/examples/python/pytorch/mnist_mlp.py
2. The second way is just a combination of the two steps in the first way, check this example:
https://github.com/flexflow/FlexFlow/blob/master/examples/python/pytorch/mnist_mlp_torch2.py
However, if you use the second way, you need to install a CPU only Pytorch because there is a conflict between Pytorch's runtime and FlexFlow's runtime. The first way has no such restrictions, because in the first step, you can just execute the code with native python interpreter, and you only need to execute the code in the second step using our modified python interpreter (flexflow_python).

By the way, since you have two GPUs, are you sure the code is running on the correct GPU? I do not think FlexFlow is able to run on different GPUs.

**Comment by act-reds** [comment]
> There is really no gpu arch check in python code.

My bad, I see my sentence wasn't accurate, I meant I was looking inside the *.cc files in the FlexFlow/python folder (used to generate the flexflow_python file used.


> By the way, since you have two GPUs, are you sure the code is running on the correct GPU? I do not think FlexFlow is able to run on different GPUs.

This works well with keras and native. Also the auto detection is working well so it's not about the flags either. I don't see any issue using different GPUs, which is nice. Also, the parallelism seems pretty efficient since both GPUs are used at the same % while the keras/native examples are running.

I'll provide an answer for people having the same issue... You need to install pytorch between 1.5 and 1.10... Over 1.10 some messages appear while running pytorch examples and I still have no idea why. 

Thanks for your answer now that I'm not having this error anymore, I need to understand how to use FlexFlow with Pytorch, I appreciate your answer since it's the next step I am diving in ! I can run the python scripts in the pytorch folder but I get nothing or some errors. I'll check a but how are FlexFlow examples supposed to behave.

**Comment by MiZhangWhuer** [comment]
> > There is really no gpu arch check in python code.
> 
> My bad, I see my sentence wasn't accurate, I meant I was looking inside the *.cc files in the FlexFlow/python folder (used to generate the flexflow_python file used.
> 
> > By the way, since you have two GPUs, are you sure the code is running on the correct GPU? I do not think FlexFlow is able to run on different GPUs.
> 
> This works well with keras and native. Also the auto detection is working well so it's not about the flags either. I don't see any issue using different GPUs, which is nice. Also, the parallelism seems pretty efficient since both GPUs are used at the same % while the keras/native examples are running.
> 
> I'll provide an answer for people having the same issue... You need to install pytorch between 1.5 and 1.10... Over 1.10 some messages appear while running pytorch examples and I still have no idea why.
> 
> Thanks for your answer now that I'm not having this error anymore, I need to understand how to use FlexFlow with Pytorch, I appreciate your answer since it's the next step I am diving in ! I can run the python scripts in the pytorch folder but I get nothing or some errors. I'll check a but how are FlexFlow examples supposed to behave.

Hi, act-reds, 
      Have you solved the problem? We've open the source code for data-parallel, model-parallel and hybrid-parallel in luojianet repository: https://github.com/WHULuoJiaTeam/luojianet
      Hope this help you get rid of trouble.

**Comment by act-reds** [comment]
> Hi, act-reds, Have you solved the problem? We've open the source code for data-parallel, model-parallel and hybrid-parallel in luojianet repository: https://github.com/WHULuoJiaTeam/luojianet Hope this help you get rid of trouble.

Hi MiZhangWhuer, 

I managed to solve the problem, yes. I still can't use the python API of FlexFlow to use parallelism for transformers, and I am now working on the modifications required to adapt the framework for this purpose.

I'll have a look on your repository to see how you guys implemented it. 

Thanks for the update concerning your tool !
