### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by Tron-x** [flexflow/FlexFlow#175]
When I installed flexflow using this linked tutorial
https://github.com/flexflow/FlexFlow/blob/master/INSTALL.md

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "RealmRuntime" in directory /data/FlexFlow/deps/legion/runtime

-- Configuring incomplete, errors occurred!
 I have already export the LG_RT_DIT variables
so the What is the problem and what should I do，ths

**Comment by eddy16112** [comment]
Could you please paste the entire cmake message here? It looks like the CUDA LIBRARY is not found.

**Comment by Tron-x** [comment]
Defaults for Linux machine
cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DCMAKE_BUILD_TYPE=Debug -DFF_CUDA_ARCH=75 -DCUDA_PATH=/data/cuda/cuda-10.1/cuda -DCUDNN_PATH=/data/cuda/cuda-10.1/cudnn/v7.6.3 -DFF_USE_PYTHON=ON -DFF_USE_NCCL=ON -DFF_USE_GASNET=OFF -FF_BUILD_EXA
MPLES=OFF -DFF_USE_AVX2=OFF -DFF_MAX_DIM=4 ../config/../
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- ZLIB libraries : /usr/lib/x86_64-linux-gnu/libz.so
-- Found CUDA: /data/cuda/cuda-10.1/cuda (found version "10.1")
-- CUDA root path : /data/cuda/cuda-10.1/cuda
-- CUDA include path : /data/cuda/cuda-10.1/cuda/include
-- CUDA runtime libraries :
-- CUDA driver libraries : /data/cuda/cuda-10.1/cuda/lib64/stubs/libcuda.so
-- CUBLAS libraries : /data/cuda/cuda-10.1/cuda/lib64/libcublas.so
-- CURAND libraries : /data/cuda/cuda-10.1/cuda/lib64/libcurand.so
-- CUDA Arch : 75
CUDA_GENCODE: -gencode arch=compute_75,code=sm_75
-- CUDNN inlcude : /data/cuda/cuda-10.1/cudnn/v7.6.3/include
-- CUDNN libraries : /data/cuda/cuda-10.1/cudnn/v7.6.3/lib64/libcudnn.so
NCCL install dir: /data/FlexFlow/build/deps/nccl
GASNET ROOT:
-- Performing Test COMPILER_SUPPORTS_MARCH
-- Performing Test COMPILER_SUPPORTS_MARCH - Success
-- Performing Test COMPILER_SUPPORTS_MALTIVEC
-- Performing Test COMPILER_SUPPORTS_MALTIVEC - Failed
-- Performing Test COMPILER_SUPPORTS_MABI_ALTIVEC
-- Performing Test COMPILER_SUPPORTS_MABI_ALTIVEC - Failed
-- Performing Test COMPILER_SUPPORTS_MVSX
-- Performing Test COMPILER_SUPPORTS_MVSX - Failed
-- Performing Test COMPILER_SUPPORTS_DEFCHECK
-- Performing Test COMPILER_SUPPORTS_DEFCHECK - Failed
-- Found PythonInterp: /usr/bin/python (found version "2.7.17")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9")
CMake Warning (dev) at deps/legion/CMakeLists.txt:246 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable CUDA_ROOT is set to:

    /data/cuda/cuda-10.1/cuda

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.19/Modules/FindCUDA.cmake:877 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'CUDA_USE_STATIC_CUDA_RUNTIME'.
Call Stack (most recent call first):
  deps/legion/cmake/FindCUDA.cmake:22 (include)
  deps/legion/CMakeLists.txt:246 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Performing Test COMPILER_SUPORTS_OVERLOADED_VIRTUAL_WARNING
-- Performing Test COMPILER_SUPORTS_OVERLOADED_VIRTUAL_WARNING - Success
-- pybind11 v2.6.2
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "RealmRuntime" in directory /data/FlexFlow/deps/legion/runtime

CMake Error in python/CMakeLists.txt:
  Imported target "pybind11::module" includes non-existent path

    "/usr/include/python2.7"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in python/CMakeLists.txt:
  Imported target "pybind11::module" includes non-existent path

    "/usr/include/python2.7"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by Tron-x** [comment]
config.linux

#!/bin/bash

echo " Defaults for Linux machine"

# set the CC and CXX, usually it is not needed as cmake can detect it
# set CC and CXX to mpicc and mpic++ when enable gasnet
# CC=mpicc
# CXX=mpic++

# add flags if needed
#CC_FLAGS=${CC_FLAGS+=""}
#NVCC_FLAGS=${NVCC_FLAGS+=""}
#LD_FLAGS=${LD_FLAGS+=""}

# set build type
BUILD_TYPE=Debug

# set CUDA Arch, replace xx with your GPU architecture
FF_CUDA_ARCH=75

# set CUDNN dir in case cmake cannot autodetect a path
CUDNN_DIR=/data/cuda/cuda-10.1/cudnn/v7.6.3

# set CUDA dir in case cmake cannot autodetect a path
CUDA_DIR=/data/cuda/cuda-10.1/cuda

LG_RT_DIR=/data/FlexFlow/deps/legion/runtime



# enable Python
FF_USE_PYTHON=ON

# enable NCCL
FF_USE_NCCL=ON

# enable GASNet
FF_USE_GASNET=OFF

# build C++ examples
FF_BUILD_EXAMPLES=OFF

# enable avx2
FF_USE_AVX2=OFF

# set MAX_DIM
FF_MAX_DIM=4

. $(dirname $0)/config.inc
run_cmake $*

**Comment by eddy16112** [comment]
Looks like the cmake uses the python2.7, and it is not supported by FlexFlow. It is recommended to create a conda env with python>=3.6 for FlexFlow.

**Comment by Tron-x** [comment]
-- Found PythonInterp: /usr/bin/python (found version "3.6.9")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9")
CMake Warning (dev) at deps/legion/CMakeLists.txt:246 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable CUDA_ROOT is set to:

    /data/cuda/cuda-10.1/cuda

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.19/Modules/FindCUDA.cmake:877 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'CUDA_USE_STATIC_CUDA_RUNTIME'.
Call Stack (most recent call first):
  deps/legion/cmake/FindCUDA.cmake:22 (include)
  deps/legion/CMakeLists.txt:246 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Performing Test COMPILER_SUPORTS_OVERLOADED_VIRTUAL_WARNING
-- Performing Test COMPILER_SUPORTS_OVERLOADED_VIRTUAL_WARNING - Success
-- pybind11 v2.6.2
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "RealmRuntime" in directory /data/FlexFlow/deps/legion/runtime

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by Tron-x** [comment]
Looks like the legion library was not found？

**Comment by eddy16112** [comment]
Looks like the Legion CMake can not find CUDA_CUDA_LIBRARY, but I do not understand why it happens. Based on your previous output, FlexFlow already finds the CUDA. Even though FlexFlow and Legion find CUDA separately, they both use the built-in FindCUDA.cmake. After googled the "CUDA_CUDA_LIBRARY", I think one solution is to use ccmake and manually set it to /data/cuda/cuda-10.1/cuda/lib64/stubs/libcuda.so

**Comment by Tron-x** [comment]
![image](https://user-images.githubusercontent.com/7659413/116061711-c6d3e900-a6b5-11eb-8f4f-22ffdea82302.png)
so  What is the problem?

**Comment by eddy16112** [comment]
Please pull and try again.

**Comment by roman955b** [comment]
@Tron-x  How did you solve this in the end?

**Comment by Sakura-gh** [comment]
I meet the same problem, so how can I deal with it ?

~~~bash 
root@28c67ac89ed8:/home/gehao/FlexFlow/build# ../config/config.linux
 Defaults for Linux machine
cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DCMAKE_BUILD_TYPE=Release -DCUDA_PATH=/usr/local/cuda-11.1 -DCUDNN_PATH=/usr/local/cuda-11.1 -DFF_USE_PYTHON=ON -DFF_USE_NCCL=ON -DFF_USE_GASNET=OFF -DFF_BUILD_ALL_EXAMPLES=ON -DFF_USE_AVX2=OFF -DFF_MAX_DIM=8 ../config/../
-- ZLIB libraries : /usr/lib/x86_64-linux-gnu/libz.so
-- CUDA Detected CUDA_ARCH : 60
-- CUDA root path : /usr/local/cuda-11.1
-- CUDA include path : /usr/local/cuda-11.1/include
-- CUDA runtime libraries :
-- CUDA driver libraries : /usr/local/cuda-11.1/lib64/stubs/libcuda.so
-- CUBLAS libraries : /usr/local/cuda-11.1/lib64/libcublas.so
-- CURAND libraries : /usr/local/cuda-11.1/lib64/libcurand.so
-- CUDA Arch : 60
-- CUDA_GENCODE: -gencode arch=compute_60,code=sm_60
-- CUDNN inlcude : /usr/local/cuda-11.1/include
-- CUDNN libraries : /usr/local/cuda-11.1/lib64/libcudnn.so
-- NCCL install dir: /home/gehao/FlexFlow/build/deps/nccl
-- GASNET ROOT:
CMake Warning (dev) at deps/legion/CMakeLists.txt:311 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable CUDA_ROOT is set to:

    /usr/local/cuda-11.1

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/gehao/anaconda3/envs/unity/lib/python3.6/site-packages/cmake/data/share/cmake-3.24/Modules/FindCUDA.cmake:1020 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'CUDA_USE_STATIC_CUDA_RUNTIME'.
Call Stack (most recent call first):
  deps/legion/cmake/FindCUDA.cmake:22 (include)
  deps/legion/CMakeLists.txt:311 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/gehao/anaconda3/envs/unity/lib/python3.6/site-packages/cmake/data/share/cmake-3.24/Modules/FetchContent.cmake:1264 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  cmake/json.cmake:3 (FetchContent_Declare)
  CMakeLists.txt:103 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using the single-header code from /home/gehao/FlexFlow/build/_deps/json-src/single_include/
-- FlexFlow MAX_DIM: 8
-- pybind11 v2.6.2
CMake Warning (dev) at /home/gehao/anaconda3/envs/unity/lib/python3.6/site-packages/cmake/data/share/cmake-3.24/Modules/CMakeDependentOption.cmake:89 (message):
  Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
  Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  deps/pybind11/CMakeLists.txt:98 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "RealmRuntime" in directory /home/gehao/FlexFlow/deps/legion/runtime

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
~~~

**Comment by jiazhihao** [comment]
@Sakura-gh It seems the cmake didn't detect the CUDA runtime libraries. You need to update `CUDNN_DIR` and `CUDA_DIR` in `config/config.linux` to dirs that hold the CUDNN and CUDA header files and libraries. This should let cmake find the correct paths.
