### ISSUE TITLE
out of memory error when running with MCMC search budget flag

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#196]
I am currently trying to run the following test file:
./flexflow_python $FF_HOME/examples/python/keras/func_mnist_cnn.py -ll:py 1 -ll:gpu 4 -ll:fsize 2048 -ll:zsize 12192 --export /usr/FlexFlow/strategy.txt --budget 1

and I get the following memory error:
num_nodes = 1 num_gpus_per_node = 4
[0 - 7f83cd7fe700]    5.699004 {6}{inst}: instance allocation failed - out of memory in mem 1e00000000000001

when I remove the budget flag, the script works well

**Comment by jiazhihao** [comment]
When `--budget` is present, FlexFlow will run an MCMC search with a simulator. The simulator by default requires 2GB of GPU memory, which is why you run out of memory. You can fix this by increasing your GPU memory allocation (`-ll:fsize`) or reduce the simulator workspace size to 1GB or smaller numbers (e.g., `--simulator-workspace-size 1073741824` )
