### ISSUE TITLE
Investigate if project board can automatically handle blocking/unblocking issues

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#463]

**Comment by virena** [comment]
For blocked issues, we can add a GitHub action (like [this one](https://github.com/marketplace/actions/blocking-issues)) or create a `blocked` label. The action is for PRs being blocked by issues, though, not issues being blocked by other issues. 

The `blocked` label wouldn't be an automation. I don't think there's an effective way to link issues to others besides referencing them in the issue description, maybe under a "blocked" header. Our current solution is a little ineffective because the project board keeps the blocked issue as a number. I'd rather have this in the issue description itself.

**Comment by lockshaw** [comment]
@virena True, though it is nice that it surfaces it into the overall table views
