### ISSUE TITLE
Remove support for cuda versions < 60

### ISSUE THREAD

**Issue by lockshaw** [flexflow/FlexFlow#481]
As discussed in the 2022-11-17 FlexFlow meeting (originally motivated by issues in #472).

This consists of parts: 
1. Limit the gpu archs built by the Makefile (I think only in CI?) to >= 60
2. Add checks for minimum gpu archs in CMake and Makefile build systems
3. Add disclaimer in README stating the supported (and unsupported) gpu archs

**Comment by daiyaanarfeen** [comment]
I think this line in the code means it is already limiting the gpu arch (to 70) in CI (https://github.com/flexflow/FlexFlow/blob/master/.github/workflows/build.yml#L58)
I thought the gpu arch needs to be limited to >=60 for any build because otherwise it will fail due to fp16 not being supported on older archs
