### ISSUE TITLE
Some Doubts About the mcmc_optimize Function

### ISSUE THREAD

**Issue by AngryBear2** [flexflow/FlexFlow#831]
Hello, I have some confusion about emulators and optimizers. In the master branch of the code, I couldn't find where the `mcmc_optimize` function was called. As a very core feature of FlexFLow, is it pluggable, and if I want to use it, should I call the `mcmc_optimize` function myself in `top_level_task`, or should I start a task through a `TaskLauncher`?

**Comment by AngryBear2** [comment]
I saw the `FFModel::compile` function in model.cc, where `graph_optimize_task` seems to replace the work of `mcmc_optimize`, and maybe I should read the paper **_Unity: Accelerating DNN Training Through Joint Optimization of Algebraic Transformations and Parallelization_**

**Comment by lockshaw** [comment]
> I saw the `FFModel::compile` function in model.cc, where `graph_optimize_task` seems to replace the work of `mcmc_optimize`, and maybe I should read the paper **_Unity: Accelerating DNN Training Through Joint Optimization of Algebraic Transformations and Parallelization_**

Yes, this is correct. In the future we're hoping to maintain implementations of both, but currently `master` only implements Unity's search algorithm.

**Comment by Resurgence27** [comment]
@lockshaw 
Hello! I have some questions below, sincerely looking for your reply!
1. I wonder if `graph_optimize` supports pipeline, tensor, data parallelism while `mcmc_optimize` doesn't?
2. when I set `only_data_parallel` to false within  `example/cpp/Transform/transforner.cc` to execute `graph_optimize`, it always incurs error like
> !para.is_valid(input_shape)

  I found this error from  function `find_match` , does  it mean could not find substitute graph for current PCG?

**Comment by lockshaw** [comment]
> @lockshaw Hello! I have some questions below, sincerely looking for your reply!
> 
>     1. I wonder if `graph_optimize` supports pipeline, tensor, data parallelism while `mcmc_optimize` doesn't?

`mcmc_optimize` is sufficiently out-of-date that I don't think it's correct to say it supports anything. Conceptually it supports pretty much anything due to the algorithm's simplicity, but concretely I think it just crashes currently. We're planning on reviving `mcmc_optimize` on #622, but it's not currently a high priority.

>     2. when I set `only_data_parallel` to false within  `example/cpp/Transform/transforner.cc` to execute `graph_optimize`, it always incurs error like
> 
> 
> > !para.is_valid(input_shape)
> 
> I found this error from function `find_match` , does it mean could not find substitute graph for current PCG?

No, likely this is some minor low-level bug that is causing a failed assertion. We're currently not really maintaining the search/optimizer code on `inference` (as the search code there is a mess and has a lot of bugs like this) and are focusing on the implementation on #622. We're hoping that the compiler on #622 will be ready for external use within the next month or two.
